version: '3.8'

services:
  backend:
    build:
      context: ./stylemate/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: railway
      MYSQL_USER: railway
      MYSQL_PASSWORD: your_mysql_password
      MYSQL_HOST: db
      MYSQL_PORT: 3306

  frontend:
    build:
      context: ./stylemate/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: "http://backend:8000"

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: railway
      MYSQL_USER: railway
      MYSQL_PASSWORD: your_mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
